### PR TITLE
Add a path in option for custom html template

### PR DESCRIPTION
**Pull request by ulissesc**
In this feature we can change the html template for custom print styles.

### CODE REVIEW

**Comment by buibr** [comment]
@Hubertformin I think this is very important, Why is not merged is there any reason?

**Comment by LucielSantos** [comment]
UP!

**Comment by Hubertformin** [comment]
Hello @ulissesc , @buibr & @LucielSantos 
I sincerely apologize for my inactivity. I will update this ASAP!

**Review by Hubertformin — APPROVED** [review]
Thank you this update, I will update the README.md with your changes

**Pull request merged**
